# Generated by Django 5.0.4 on 2024-05-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_user_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_prep',
            field=models.TextField(default=''),
        ),
    ]
